name: "github-ejs-build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write    
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - name: Check cosign install!
        run: cosign version            
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
            JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: NPM Audit 
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          JFROG_CLI_BUILD_PROJECT: dro
        run: |
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER 
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
          jf npmc --repo-resolve dro-npm-unsecure-remote
          jf npm i --omit dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=$GITHUB_RUN_NUMBER
          jf audit --npm --fail=false
      - name: Docker build 
        id: docker-build  
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          JF_HOST: ${{ secrets.JF_HOST }}
          JFROG_CLI_BUILD_PROJECT: dro
        run: |
          docker build --build-arg JF_TOKEN=${JF_ENV_1} . -t ejs-demo:$GITHUB_RUN_NUMBER
          docker tag ejs-demo:$GITHUB_RUN_NUMBER $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER
          jf docker push $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER --build-name=$JFROG_CLI_BUILD_NAME --build-number=$GITHUB_RUN_NUMBER 
          docker images --no-trunc --quiet $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER
          echo "digest=$(docker images --no-trunc --quiet $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          # The subject name must be the image name
          subject-name: ${{ secrets.JF_HOST }}/dro-oci-dev-local/ejs-demo
          subject-digest: ${{ steps.docker-build.outputs.digest }}
          push-to-registry: true
      - name: Publish build info
        id: publish-build  
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JFROG_CLI_BUILD_PROJECT: dro
        run: |
           cat ${{ steps.attest.outputs.bundle-path }}
           jf rt bp $JFROG_CLI_BUILD_NAME $GITHUB_RUN_NUMBER