name: "github-ejs-build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read 
      attestations: write    
      packages: write
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18 
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_PROJECT: ${{ vars.JF_PROJECT_KEY }}
        with:
            oidc-provider-name: davidro-github-integration
            oidc-audience: davidro-github
      - name: NPM Audit 
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_URL: https://${{ vars.JF_URL }}/
          JF_HOST: ${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT_KEY }}
        run: |
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER 
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
          jf npmc --repo-resolve dro-npm-unsecure-remote
          jf npm i --omit dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=$GITHUB_RUN_NUMBER
          jf audit --npm --fail=false
      - name: Docker build 
        id: docker-build  
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_HOST: ${{ secrets.JF_HOST }}
          JF_PROJECT: ${{ vars.JF_PROJECT_KEY }}
        run: |
          docker build --build-arg JF_TOKEN=${JF_ENV_1} . -t ejs-demo:$GITHUB_RUN_NUMBER
          docker tag ejs-demo:$GITHUB_RUN_NUMBER $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER
          jf docker push $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER --build-name=$JFROG_CLI_BUILD_NAME --build-number=$GITHUB_RUN_NUMBER 
          docker images --no-trunc --quiet $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER
          echo "digest=$(docker images --no-trunc --quiet $JF_HOST/dro-oci-dev-local/ejs-demo:$GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          # The subject name must be the image name without tag
          subject-name: ${{ secrets.JF_HOST }}/dro-oci-dev-local/ejs-demo
          subject-digest: ${{ steps.docker-build.outputs.digest }} #format must be SHA256:<hexvalue>
          push-to-registry: false
      - name: Publish build info
        id: publish-build  
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_PROJECT: ${{ vars.JF_PROJECT_KEY }}
        run: |
           cat ${{ steps.attest.outputs.bundle-path }}
           jf rt bp $JFROG_CLI_BUILD_NAME $GITHUB_RUN_NUMBER